### ISSUE TITLE
unit tests don't run, need more test coverage

### ISSUE THREAD

**Issue by hokiegeek2** [Marcnuth/AnomalyDetection#18]
When I attempt to run the test_detect_ts I get the following error:

Traceback (most recent call last):
  File "/var/development/git/hokiegeek2-forks/AnomalyDetection/tests/test_detect_ts.py", line 34, in <module>
    test_anomaly_detect_ts(data)
  File "/var/development/git/hokiegeek2-forks/AnomalyDetection/tests/test_detect_ts.py", line 24, in test_anomaly_detect_ts
    results = detts.anomaly_detect_ts(data, max_anoms=0.02,
AttributeError: 'function' object has no attribute 'anomaly_detect_ts'

Also, definitely need more unit test coverage

**Comment by hokiegeek2** [comment]
Just submitted pull request

**Comment by hokiegeek2** [comment]
merged, thanks @Marcnuth
